(function(){var b=window.cfx;b.animationVersion="7.1.5044.21402";var e=window.sfx;b.AnimationDelay={Auto:0,None:4096,PerPoint:1,PerSeries:2,PerPointInverse:17,PerPointRandom:33,PerPointSeries:3};b.AnimationDirection={Auto:0,Upward:1,Downward:2,FromCenter:3};b.AnimationTiming={Auto:0,Linear:1,EaseIn:2,EaseOut:3,EaseInEaseOut:4,EaseOutBounce:5};b.BarAnimation={Value:0,Drop:1};b.BubbleAnimation={Position:0,Size:1,PositionAndSize:2};b.LineAnimation={DrawX:0,YData:1,YProgress:2};b.PieAnimation={Radial:1,
Angle:2,RadialAndAngle:3,AngleFromTop:258,RadialAngleFromTop:259};var j=function r(){r._ic();this.d=this.e=0;this.a=!1;this.c=0};b.AnimationSettings=j;j.prototype={_0AnimationSettings:function(){this.b=1.2;return this},getDelay:function(){return this.e},setDelay:function(b){this.e=b},getDirection:function(){return this.d},setDirection:function(b){this.d=b},getDuration:function(){return this.b},setDuration:function(b){this.b=b},getEnabled:function(){return this.a},setEnabled:function(b){this.a=b},
getTiming:function(){return this.c},setTiming:function(b){this.c=b}};j._dt("CWA",e.Sy,0);var l=function s(){s._ic();this.n=!1;this.a=this.m=this.e=this.c=null;this.f=this.l=!1;this.d=null;this.j=this.k=0;this.i=null;this.g=this.h=!1};b.AnimationAttributes=l;l.prototype={_0AnimationAttributes:function(b){this.b=b;return this},r:function(){null==this.c&&(this.c=(new h)._0co(this,this.m));return this.c},getDataChange:function(){null==this.a&&(this.a=(new j)._0AnimationSettings(),this.a.b=0.4);return this.a},
getLoad:function(){null==this.d&&(this.d=(new j)._0AnimationSettings());return this.d},getShowSpeed:function(){return this.g},setShowSpeed:function(b){this.g=b},o:function(){var b=this.b.r;this.j=b.iaM();this.k=b.iaH();this.i=b.iaO().j(this.j,this.k,!1,!0);this.e=Array(2*this.b.getAxesY().Se());for(var b=0,d=this.b.getAxesY().Sb();!0==d.SI();){var a=d.SK();this.e[b++]=a.z;this.e[b++]=a.E}},q:function(b,d){if(this.n)return!0;this.f=b;this.h&&(this.h=!1,this.f=!0);if(this.f){this.m=this.d;var a=null!=
this.d&&this.d.a;!a&&(null!=this.a&&this.a.a&&null==this.i)&&this.o();return a&&!this.l}if(d){if(null==this.a||!this.a.a)return!1;var c=this.b.r,a=!1;if(this.j!=c.iaM()||this.k!=c.iaH())a=!0;else for(var c=0,f=this.b.getAxesY().Sb();!0==f.SI();){var g=f.SK();if(this.e[c++]!=g.z){a=!0;break}if(this.e[c++]!=g.E){a=!0;break}}if(a)return this.o(),!1;this.m=this.a;return!0}return!1},p:function(b,d){null!=this.c&&!this.c.al(b,d)&&(null!=this.a&&this.a.a&&this.o(),this.l=!0,this.c=null,this.n=!1)},reset:function(){this.l=
!1;this.c=null;this.h=!0;this.b.c(32)}};l._dt("CWA",e.Sy,0);var m=function d(){d._ic();this.d=null;this.e=this.a=this.b=0;this.i=!1;this.o=this.k=null;this.f=this.g=0;this.n=null;this.c=this.h=0};b.cn=m;m.prototype={_0cn:function(d){this.m=d;return this},getCompactFormula:function(){return this.d.getCompactFormula()},setCompactFormula:function(d){this.d.setCompactFormula(d)},getHasData:function(){return!0},getShared:function(){return this.d.getShared()},setShared:function(d){this.d.setShared(d)},
getItem1:function(d){return this.d.getItem1(d)},setItem1:function(d,a){this.d.setItem1(d,a)},getItem:function(d,a){var c=0;if(null!=this.d){if(c=this.d.getItem(d,a),0!=(this.e&32))return c+=this.k.getItem(d,a)}else c=this.f;if(b.c6.d(c))return c;var f=this;if(0!=this.m.L){if(0==(this.m.L&1<<d))return c;null!=this.o&&0!=d&&(f=this.o[d-1])}var g=this.m.N(d,a,this.c);return f.p(d,a,c,g)},setItem:function(d,a,c){this.d.setItem(d,a,c)},q:function(d){return this.f!=d.f||this.g!=d.g||this.i!=d.i||this.h!=
d.h||this.e!=d.e||this.b!=d.b||this.c!=d.c||this.a!=d.a?!1:!0},p:function(d,a,c,f){var b=0,i=0,i=null!=this.n?this.n[d][a]:this.f;3==this.a&&(b=(this.g+this.f)/2);d=0;this.i&&(d=0<c?this.g:this.f);if(0>=f){if(this.i)return 2==this.a?d:0;switch(this.a){case 1:return i;case 2:return this.g;case 3:return b}}if(0!=(this.e&2))return d=0,2==this.a?(d=this.g-f*this.h,d<c&&(d=c)):1==this.a?(d=i+f*this.h,d>c&&(d=c)):(i=e.a.n(this.g-b,b-this.f),c<b?(d=b-f*i,d<c&&(d=c)):(d=b+f*i,d>c&&(d=c))),d;if(this.i)return 2==
this.a?d-f*(d-c):f*c;switch(this.a){case 2:return this.g-f*(this.g-c);case 3:return b+f*(c-b)}return i+f*(c-i)},clear:function(){this.d.clear()},l:function(b){this.f=b.k;this.g=b.m;this.i=0<this.g&&0>this.f;this.h=this.g-this.f}};m._dt("CWIA",e.Sy,0);var h=function a(){a._ic();this.f=!1;this.D=this.e=this.y=this.h=this.d=this.m=0;this.v=null;this.q=0;this.x=!1;this.ab=0;this.j=null;this.Z=this.aa=this.k=0;this.M=null;this.Y=this.u=0;this.C=null;this.c=this.I=0;this.a=null;this.L=0;this.X=null;this.B=
!1;this.K=null;this.p=this.g=0;this.o=null;this.H=!1;this.w=this.W=null;this.G=0;this.V=null;this.F=0};b.co=h;h.prototype={_0co:function(a,c){this.b=new e.c;this.C=a;this.X=c;this.h=c.b;this.d=c.e;this.p=c.c;this.D=1;this.Y=0.35;return this},aj:function(a){this.B&&(a.h.t=this.Z,a.a.y=this.aa);1<=this.c&&this.R(a.c)},t:function(a,c){switch(c){case 2:return a*a;case 3:return-a*(a-2);case 4:a/=0.5;if(1>a)return 0.5*a*a;a--;return-0.5*(a*(a-2)-1);case 5:return this.ao(a)}return a},ap:function(a){if(1<=
this.c)return null!=this.v?(a.P=!1,this.v=e.V.C(a.c,b.ic5),this.v.ic7(1),this.R(a.c),!1):!0;var c=a.h,f=null==this.K,g=0;if(f){this.C.n=!0;this.K=e.ah.L();this.I=e.a.d(a.o-a.m)+1;var i=!1,g=!this.C.f;if(0==(a.bR&524288)||g)this.a=(new m)._0cn(this),this.a.a=this.X.d,0!=(a.i&64)&&(i=!0);else{var h=a.bz.getSeries();this.j=Array(h.Se());for(var o=null,p=!0,j=null,k=0;k<h.Se();){var n=h.getItem(k).getGalleryAttributes(),n=e.V.C(n,b.icT);null==n&&(null==j&&(j=a.bz.getGalleryAttributes(),j=e.V.C(j,b.icT)),
n=j);var l=h.getItem(k).getGallery(),q=(new m)._0cn(this);a.ab&&q.l(c);this.a=this.j[k]=q;this.T(a,n,l,c);null!=o&&p&&(p=this.a.q(o));0!=(n.icW(l)&64)&&(i=!0);k+=n.icV(l);o=this.a}p&&(this.j=null)}this.V=a.ad;this.W=a.M;if(a.ab){if(this.u=0,h=e.a.o(a.aq,a.ar),o=e.a.o(a.z,a.D),p=e.a.d(a.ar-a.aq),k=e.a.d(a.D-a.z),this.b._i2(h,o,p,k),c.I(a.a)&&(this.b.w=k,this.b.h=p,this.b.x=o,this.b.y=h),i)i=a.b.i,a.j.valueToPixel(1)-i<this.b.x&&this.b.m(i,0),0==(this.e&1)&&this.b.m(0,i+2)}else this.b._cf(a.v);null==
this.j&&this.a.l(c);g&&(this.q|=4,this.a.n=this.C.i);null==this.j&&(this.T(a,a.b.j,a.b.p,c),this.U(),this.af(a));a.ab?(this.G=e.a.o(a.aq,a.ar),this.F=e.a.o(a.z,a.D)):(this.G=a.v.x,this.F=a.v.y);if(0!=(this.e&64))return this.c=1,!0;g=0}else this.H&&this.Q(),g=this.t(this.c,this.p);1>g&&(a.P=!0,a.aG=this.f);this.ab++;null==this.j&&!this.f&&0!=(this.e&1)&&(0!=(this.d&2)?f&&this.ag(a):this.x&&!f&&this.J(a,g));return 0!=(a.r&128)?(a.P=!1,this.v=e.V.C(a.c,b.ic5),this.v.ic7(this.ac()),0==this.c):!0},ai:function(a){if(1<=
this.c)if(0!=(this.q&1))this.q&=-2;else return!1;var c=!1;null!=this.j?(c=!0,a.ab||this.ae(a)):c=this.ah(a);return c},ah:function(a){var c=!1;if(this.f){if(a.ad=this.a,null!=this.a.k&&(a.ay=this.a.k),null!=this.w)a.M=this.w}else if(0!=(this.e&1))if(0!=(this.d&2))c=!0;else{if(0==this.c&&null==this.j||!this.x){var b=this.t(this.c,this.D);this.J(a,b)}}else if(this.B){var b=this.t(this.c,this.p),g=a.h;this.Z=g.t;this.aa=a.a.y;b*=e.a.d(a.D-a.z);b=e.a.n(b,1);g.br(b,!1);2==this.a.a?a.a.y=a.a.L+b:3==this.a.a&&
(a.a.y=e.u.z(a.a.y+a.a.L+b,2))}return c},ao:function(a){if(a<h.l)return h.i*a*a;if(a<h.n)return a-=h.A,h.i*a*a+h.P;if(a<h.r)return a-=h.z,h.i*a*a+h.O;a-=h.E;return h.i*a*a+h.ad},ag:function(a){a=e.a.d(a.q-a.p)+1;this.m=3==(this.d&3)?a*this.I:0!=(this.d&2)?a:this.I;this.an(this.m);if(0!=(this.d&32)){this.o=Array(this.m);for(a=0;a<this.m;a++)this.o[a]=a;for(var c=(new e.U)._0U(),a=0;a<this.m;a++){var b=c.c(this.m-a),g=this.o[a];this.o[a]=this.o[b];this.o[b]=g}}},af:function(a){this.H=this.B=this.x=
!1;a.aG=!1;0!=(a.r&128)?this.H=this.f=!1:(this.f=(4096!=this.d||a.g(256)||0!=(this.e&2))&&0==(this.e&1)&&a.ab,0!=(this.e&8)&&(this.f=!0),0!=(this.e&16)&&(this.f=!1),0!=(this.q&4)&&(this.f=!0,this.e&=-2),this.B=a.ab&&!this.f,0!=(this.e&1)&&(this.B=!1,4096==this.d&&null==this.j&&0==(a.r&64)&&(this.x=!0)),(this.f||!a.ab)&&4096!=this.d&&this.ag(a),this.f&&(this.a.d=a.ad,0!=(this.e&4)&&a.M.getHasData()&&(this.w=(new m)._0cn(this),this.w.d=a.M,this.w.l(a.j),this.w.a=this.a.a,0==(this.q&2)&&(this.q|=2,this.b.m(5,
0)))),a.aG=this.f)},an:function(a){var c=a*this.Y,b=0;1.3>c?(c=2.5,this.g=3.5*(this.h/5)):this.g=2*(this.h/5);this.k=0;for(var g=0.5,i=a-1,h=0;8>h;h++){this.g=e.a.n(this.g,g);b=i*this.k+this.g;if(0.2>e.a.d(b-this.h))break;this.k=this.g/c;if(this.k>=0.8*this.g)g*=1.3;else{b=i*this.k+this.g;if(0.2>e.a.d(b-this.h))break;b>this.h&&(b=(this.h-this.g)/a,0.2>b&&(c*=1.5),this.k=(this.k+b)/2);this.g=this.h-i*this.k}}},ae:function(a){0!=(this.e&1)&&a.c.sic$(null);this.f&&(a.ad=this.V,a.M=this.W);null!=this.j&&
(this.a=this.j[a.d],this.U(),this.af(a),this.ah(a));if(0!=(this.e&1)){var b=this.N(a.d,0,this.p);a.c.sic$(null);this.J(a,b)}},am:function(){0==this.a.b&&(this.a.b=1);0==this.a.c&&(this.a.c=4);0==this.a.a&&(this.a.a=1)},ac:function(){return this.t(this.c,this.p)},N:function(a,b,f){if(4096==this.d)return this.t(this.c,f);var g=0,g=3==(this.d&3)?a*this.I+b:0!=(this.d&1)?b:a;0!=(this.d&16)&&(g=this.m-g-1);null!=this.o&&(g=this.o[g]);a=g*this.k;if(this.y<=a)return 0;b=a+this.g;if(this.y>=b)return 1;a=
(this.y-a)/(b-a);return a=this.t(a,f)},al:function(a){if(1<=this.c)return!1;var b=0;this.H||(this.Q(),b=this.t(this.c,this.p));var f=this.b._nc();if(null!=this.v)1<=this.c?(this.q|=1,f._cf(this.b)):this.v.ic6(b,f);else if(this.x&&1>b){var g=0,b=b*this.b.w;if(4096==this.d){var e=b-this.u,g=this.b.x+this.u;this.u=b;b=e+1}else g=this.b.x;f._i2(g,this.b.y,b,this.b.h)}1<=this.c&&f._cf(a.SN());a.Sab(f);return!0},U:function(){this.d=this.a.b;this.p=this.a.c;this.e=this.a.e},J:function(a,b){var f=0,g=b*this.b.w;
if(this.x){if(0!=b)return;var i=g-this.u,f=this.b.x+this.u;this.u=g;g=i+1}else f=this.b.x;f=(new e.c)._02c(f,this.b.y,g,this.b.h);f=(new e.aq)._0aq(f);a.c.sic$(f);null!=this.M&&this.M._d();this.M=f},ak:function(){this.a.b=this.d;this.a.c=this.p;this.a.e=0},T:function(a,b,f,g){this.ak();var e=null;0!=(b.icW(f)&262144)&&a.ay.getHasData()&&(e=(new m)._0cn(this),e.l(g),e.d=a.ay,this.a.k=e);0==(this.q&4)&&b.icU(f,11,this,a);null!=e&&0==e.a&&(e.a=this.a.a);this.am()},R:function(a){if(this.C.g){a.sida(null);
var b=(new e.at)._0at(),f=(new e.o)._0o("Helvetica",8),g=e.D._k(this.ab/this.h,"f2",null),h=(new e.ar)._0ar(e.m.i());a.idR(h,this.G,this.F,32,14);h._d();a.idE(g,f,e.aj.G(),this.G,this.F,b);f._d();b._d()}},Q:function(){this.y=this.K.J()/1E3;this.c=this.y/this.h;this.c=e.a.o(this.c,1);1!=this.D&&(this.c=this.t(this.c,this.D),this.y=this.h*this.c)}};h._dt("CWIA",e.Sy,0);b.Chart.prototype.getAnimations=function(){null==this.R&&(this.R=(new b.AnimationAttributes)._0AnimationAttributes(this));return this.R};
"undefined"!=typeof b.VectorGalleryConnected&&(b.VectorGalleryConnected.prototype.getAnimationStyle=function(){return this.C});"undefined"!=typeof b.VectorGalleryConnected&&(b.VectorGalleryConnected.prototype.setAnimationStyle=function(a){this.C=a});"undefined"!=typeof b.VectorBar&&(b.VectorBar.prototype.getAnimationStyle=function(){return this.o});"undefined"!=typeof b.VectorBar&&(b.VectorBar.prototype.setAnimationStyle=function(a){this.o=a});"undefined"!=typeof b.VectorBubble&&(b.VectorBubble.prototype.getAnimationStyle=
function(){return this.o});"undefined"!=typeof b.VectorBubble&&(b.VectorBubble.prototype.setAnimationStyle=function(a){this.o=a});"undefined"!=typeof b.VectorPie&&(b.VectorPie.prototype.getAnimationStyle=function(){return this.p});"undefined"!=typeof b.VectorPie&&(b.VectorPie.prototype.setAnimationStyle=function(a){this.p=a})})();
